### ISSUE TITLE
[MC-1.12.1] Invalid registration for oreResonating.

### ISSUE THREAD

**Issue by marcin212** [McJty/DeepResonance#223] opened 2017-08-14 19:21 UTC
```
[21:16:29] [main/WARN] [FML]: ****************************************
[21:16:29] [main/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name oreResonating has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[21:16:29] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:619)
[21:16:29] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[21:16:29] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:604)
[21:16:29] [main/WARN] [FML]: *  at mcjty.deepresonance.ForgeEventHandlers.registerBlocks(ForgeEventHandlers.java:37)
[21:16:29] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_388_ForgeEventHandlers_registerBlocks_Register.invoke(.dynamic)
[21:16:29] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)...
[21:16:29] [main/WARN] [FML]: ****************************************
```

**Comment by bookerthegeek** [comment] 2017-12-24 01:19
Duplicate of https://github.com/McJty/DeepResonance/issues/220

**Comment by McJty** [comment] 2017-12-24 08:05
Fixed next release

**Closed by McJty** 2017-12-24 08:05 UTC
