### ISSUE TITLE
[1.12.1] Invalid Ore Dictionary Registration

### ISSUE THREAD

**Issue by Preminenc3** [McJty/DeepResonance#224] opened 2017-08-16 23:24 UTC
[Log Code](https://pastebin.com/KxhvUVBY)

**Comment by ProsperCraft** [comment] 2017-08-29 13:19
Is this related to this magic bees crash?

https://github.com/Lach01298/MoreBees/issues/59

**Comment by bookerthegeek** [comment] 2017-12-24 01:19
Duplicate of https://github.com/McJty/DeepResonance/issues/220

**Comment by McJty** [comment] 2017-12-24 08:04
Fixed next release

**Closed by McJty** 2017-12-24 08:04 UTC
