### ISSUE TITLE
Caught exception from DeepResonance

### ISSUE THREAD

**Issue by Allalous** [McJty/DeepResonance#261] opened 2018-02-15 23:24 UTC
Hello,

I was updating my custom modpack today and when I tried to launch the pack, it crashes at the same spot every time. Here is the report.

[crash-2018-02-15_16.49.32-client.txt](https://github.com/McJty/DeepResonance/files/1729722/crash-2018-02-15_16.49.32-client.txt)

**Comment by josephcsible** [comment] 2018-02-15 23:25
Can you try uploading that again? I get an error trying to download it.

**Comment by josephcsible** [comment] 2018-02-15 23:26
Never mind, I got it.

**Comment by josephcsible** [comment] 2018-02-15 23:29
Last time I saw an error like that, it was a version mismatch or conflict. Can you make sure that you're on the latest versions of ElecCore, McJtyLib, and Deep Resonance? If so, can you try removing your other mods and seeing if any of them are causing a conflict?

**Comment by Allalous** [comment] 2018-02-15 23:31
Ok let me try that real fast.

**Comment by Allalous** [comment] 2018-02-15 23:39
I checked the version of those 3, they are all up to date and I even redownloaded them "just in case". Still the same crash. I haven't had any kind of problem with this mod until today

**Comment by josephcsible** [comment] 2018-02-15 23:59
Two things worth trying:
1. If you just upgraded any of McJtyLib, ElecCore, or Deep Resonance, try putting them individually back to their old versions
2. Try disabling all of your mods except for them

**Comment by Allalous** [comment] 2018-02-16 00:00
Ok I'll try those and let you know.

**Comment by josephcsible** [comment] 2018-02-16 00:00
If 2 works, see if Ender IO in particular is the problem.

**Comment by Allalous** [comment] 2018-02-16 00:05
Well I put McJtyLib down a version and it almost worked. Now I have a new crash.

[crash-2018-02-15_18.03.27-client.txt](https://github.com/McJty/DeepResonance/files/1729803/crash-2018-02-15_18.03.27-client.txt)

**Comment by josephcsible** [comment] 2018-02-16 00:07
That one doesn't give much insight at all. See if option 2 does anything different (try with both the old and new McJtyLib).

**Comment by Allalous** [comment] 2018-02-16 00:08
Alright.

**Comment by Allalous** [comment] 2018-02-16 00:36
Ok I think I have found the problem. I was slowly reinstalling the mods a few at a time and launching it and now my crash reports are pointing to MFR. Should I show you that crash report or show it to them?

**Comment by josephcsible** [comment] 2018-02-16 00:36
Show it to us first.

**Comment by Allalous** [comment] 2018-02-16 00:37
[crash-2018-02-15_18.33.00-client.txt](https://github.com/McJty/DeepResonance/files/1729855/crash-2018-02-15_18.33.00-client.txt)

**Comment by josephcsible** [comment] 2018-02-16 00:40
That only crashed because MFR needs EnderIO.

**Comment by Allalous** [comment] 2018-02-16 00:40
Ok Let me try it again with enderIO on

**Comment by Allalous** [comment] 2018-02-16 00:43
Ok that worked, going back to slowing turning some of the mods back on to see if their is still a problem.

**Comment by Allalous** [comment] 2018-02-16 01:22
Alright, got half way down my mod list and I got some crashes.

[crash-2018-02-15_19.18.21-client.txt](https://github.com/McJty/DeepResonance/files/1729931/crash-2018-02-15_19.18.21-client.txt)
[crash-2018-02-15_19.20.00-client.txt](https://github.com/McJty/DeepResonance/files/1729932/crash-2018-02-15_19.20.00-client.txt)
[crash-2018-02-15_19.22.04-client.txt](https://github.com/McJty/DeepResonance/files/1729933/crash-2018-02-15_19.22.04-client.txt)

**Comment by josephcsible** [comment] 2018-02-16 02:26
That's still a really big list. Keep going until removing any more mods makes it work, then post that crash.

**Comment by Allalous** [comment] 2018-02-16 02:56
I get this crash report when I try to put RFTools back on.

[crash-2018-02-15_20.54.47-client.txt](https://github.com/McJty/DeepResonance/files/1730085/crash-2018-02-15_20.54.47-client.txt)

**Comment by josephcsible** [comment] 2018-02-16 02:56
There's still a ton of other mods.

**Comment by Allalous** [comment] 2018-02-16 02:57
Yeah, I'm writing it down and starting the list over in a different order each crash

**Comment by josephcsible** [comment] 2018-02-16 04:12
I managed to reproduce your crash. The three factors in common seem to be Deep Resonance, McJtyLib 2.5.2, and EnderIO. For now, downgrading to McJtyLib 2.5.1 will fix the bug this is about (if you still get crashes after that, it's something else; open a new ticket for it). I'll try to get this fixed tomorrow.

**Comment by Allalous** [comment] 2018-02-16 04:13
On a whim, I disabled DR and the pack loaded just fine. I turned it back on and I get this crash. It's different from the very first time this started.

[crash-2018-02-15_22.00.56-client.txt](https://github.com/McJty/DeepResonance/files/1730198/crash-2018-02-15_22.00.56-client.txt)

**Comment by josephcsible** [comment] 2018-02-16 04:14
Yeah, I have no idea about that other one.

**Comment by Allalous** [comment] 2018-02-16 04:16
Ha ha alright. I'll try to see if I can another crash and show you tomorrow

**Comment by josephcsible** [comment] 2018-02-16 04:32
I think the first crash you got is because DeepResonance comes before EnderIO when sorted alphabetically, so EnderIO's API isn't loaded yet when we try to load a block that uses it. (Downgrading worked because we used to bundle that API.) The fix for this will be adding an `after:EnderIO` somewhere, which I'll test and commit tomorrow.

**Comment by Rudy2D2** [comment] 2018-02-16 04:44
I have this issue as well and can confirm that removing EnderIO or downgrading McJtyLib fixes it.
Allalous - I've had your last issue before. I was able to fix it by changing the milk and milk bucket options in the Forestry and MFR configs (forestry/fluids.cfg and powercrystals/minefactoryreloaded/common.cfg).

**Comment by Allalous** [comment] 2018-02-16 12:07
Thanks for that, I just find it very strange that I'm getting this now when neither of those 2 mods have had an update in awhile.

**Comment by josephcsible** [comment] 2018-02-16 12:16
It was the update to McJtyLib that caused it.

**Comment by mallrat208** [comment] 2018-02-16 12:48
It's worth mentioning it's been a while since Deep Resonance actually had a build pushed, the current one is from December 27th and McJtyLib has updated several times since then.

**Comment by josephcsible** [comment] 2018-02-17 04:45
The NoClassDefFoundError is fixed in McJty/McJtyLib@4414555. The NullPointerException I still have no idea about, but I don't think it's Deep Resonance-related.

**Closed by josephcsible** 2018-02-17 04:45 UTC

**Comment by Rudy2D2** [comment] 2018-02-17 10:23
Sorry to be a nag, but the new CompatLayer required for the new McJtyLib breaks Dense Ores.
