### ISSUE TITLE
Infusing Laser JEI integration is broken

### ISSUE THREAD

**Issue by Ricket** [McJty/DeepResonance#163] opened 2017-01-08 23:11 UTC
In direwolf20's mod spotlight at 18:54, he says there is JEI integration, "you can go to the infusing laser and hit U", and he shows how you can see all the catalyst's extra effects. Link to time: https://youtu.be/XIiuZZazgXY?t=1134

I tried this and pressing U or right-clicking as usual, does nothing. I can only see the recipe for the laser, not the catalysts.

I'm using DeepResonance version 1.4.2, part of Direwolf20-1.10 pack version 1.3.2. JEI is version 1.10.2-3.14.2.401.

**Comment by McJty** [comment] 2017-01-30 11:47
Hmm strange. I cannot reproduce this. Works fine for me. Did you try updating the mods?

**Comment by chebanov** [comment] 2017-01-31 10:09
Can confirm. Same when using the jei 1.10.2-3.14.3.403 and DeepResonance 1.4.4

Here the part of fml-log-lastest: http://pastebin.com/KjsRhcpX

**Comment by McJty** [comment] 2017-02-03 07:25
Found the issue. Will be fixed next release

**Closed by McJty** 2017-02-03 07:25 UTC
