### ISSUE TITLE
Depleted crystal still glowing

### ISSUE THREAD

**Issue by Xandaros** [McJty/DeepResonance#102] opened 2016-07-28 16:26 UTC
I mentioned this earlier on IRC and then couldn't reproduce it. I have now figured out how to reproduce it:
Have a reactor setup with 1 controller, 1 generator, 1 energy collector and 1 pedestal.
Like this:
[![](http://storage6.static.itmages.com/i/16/0728/s_1469723058_7518529_e7f59c4ab0.png)](http://storage6.static.itmages.com/i/16/0728/h_1469723058_7518529_e7f59c4ab0.png)

You then:
* Turn on the generator
* Wait until the generator is red
* Place a 10/10/10 crystal with exactly 0.03% energy left in the inventory of the pedestal
* Wait for the crystal to deplete and drop
* Take the crystal, place it in the world near the generator. It is glowing
* As a bonus, turn off the generator. The crystal stops glowing.

I realise that this is a ridiculous edge case, but it should be easy to fix.

**Comment by McJty** [comment] 2016-08-27 04:17
I think this is now fixed. I cannot reproduce it at least

**Closed by McJty** 2016-08-27 04:17 UTC
