### ISSUE TITLE
RCL issue after updating

### ISSUE THREAD

**Issue by FusionC** [McJty/DeepResonance#161] opened 2017-01-05 11:20 UTC
I get this symbol on my One Probe popup after updating Infinity Lite 1.10 this morning. I'm hoping this will fix itself after I build a laser. Will report back.

http://imgur.com/qLJWVRA

Edit: After doing some testing I have come to a conclusion about this bug. The liquid for whatever reason will now no longer occupy an EnderIO fluid conduit. I've never seen this happen to a liquid before. This means I cannot pump it out of the DR tanks and into a separate tank. Or even back into the purifying chamber. It's a shame losing that ore, but hopefully this helps squash a bug :)

These other images show the conduit not being filled with the liquid. You can see the conduit turns red on the borders but the inside never fills.

http://imgur.com/tAkkbdR
http://imgur.com/LRtEVoL

Edit 2: Separate Issue: I cannot even get the purifier to export spent filters to a chest via EnderIO item conduits. It just pops them out onto the floor even if I cover every single side of the purifier. I removed those buggy tanks as mentioned earlier and smelted another 10 ore and it was looking fine in One Probe for about 5 or 6 buckets into the bottom tank but now the bottom tank reads "?" again. I guess it's onto Extreme Reactors for now. Not looking forward to it :(

**Comment by McJty** [comment] 2017-01-05 15:38
What versions of the mods (eleccore, deep resonance, ...) do you have?

**Comment by FusionC** [comment] 2017-01-06 06:07
I removed them from my pack because it felt like I was getting blocked at everything I was trying to do. But if you need to know just look at the latest singleplayer Infinity Lite release. That's what I was using. You may close this issue.

**Comment by McJty** [comment] 2017-03-03 12:49
This was caused by bugs in eleccore at that time. Fixed now

**Closed by McJty** 2017-03-03 12:49 UTC
